### ISSUE TITLE
Fix get_value_ref in Fortran

### ISSUE THREAD

**Issue by mdpiper** [mcflugen/cookiecutter-bmi-wrap#11]
Calling the `get_value_ref` function in Python from a wrapped Fortran library fails with the following trace:

```
Traceback (most recent call last):
  File "heatf_ex.py", line 86, in <module>
    ref = m.get_value_ref(var_name)
  File "pymt_heatf/lib/heat.pyx", line 375, in pymt_heatf.lib.heat.Heat.get_value_ref
  File "pymt_heatf/lib/heat.pyx", line 390, in pymt_heatf.lib.heat.Heat.get_value_ref
ValueError: Cannot create cython.array from NULL pointer
```

Assign @mdpiper to fix this!

**Comment by mdpiper** [comment]
Using matched C and Fortran compilers (in this case, the [Anaconda compilers](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html)) fixed this issue. I had, unknowingly, been using a mix of compilers and libraries from Anaconda and the OS.
